### ISSUE TITLE
Unable to remove workflow parameters in UI

### ISSUE THREAD

**Issue by chris-downs** [StackStorm/ewc#2] opened 2017-04-11 14:14 UTC
When clicking the `x` next to a parameter in the Metadata dialog of the Workflow Composer the parameter is not removed. 

![screen shot 2017-04-11 at 9 57 53 am](https://cloud.githubusercontent.com/assets/4074377/24913630/b7b3322a-1e9f-11e7-8177-de9d135f52a0.png)

**Comment by bigmstone** [comment] 2017-04-11 15:56
@chris-downs thanks for the report. Can you provide the browser (with version) and OS you're using? I'll see if I can reproduce it and get to the bottom of what's going on.

**Comment by chris-downs** [comment] 2017-04-11 16:00
Sure, running Chrome 57.0.2987.133 (64-bit) on OS X 10.12.4. I can also repro in Safari 10.1.1 (12603.2.1)

**Comment by bigmstone** [comment] 2017-04-11 16:00
Thanks @chris-downs. I'll keep you posted.

**Comment by bigmstone** [comment] 2017-04-13 23:11
@chris-downs I was able to run down the issue today. It appears to be a transpiling issue between lodash and underscore. It transpiles into using `omit` instead of `omitBy`. It looks like the proper solution is to move away from `underscore` to `lodash` and use `omitBy` in our ES6 code which will transpile into `omitBy` in the ES5 compatible code. I'll work on this solution and keep you posted. /cc @enykeev

**Comment by chris-downs** [comment] 2017-04-14 01:37
Great! Thanks for the update.

**Comment by bigmstone** [comment] 2017-04-14 15:33
@chris-downs I've added the fix. Looks like we were already using lodash just not using the `omitBy`. This will be in release 2.3 which is just around the corner.

**Closed as completed** 2017-04-14 15:32 UTC
Labels: flow, SUPPORT
